[build]
  publish = "public"
  command = "gatsby build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"

[[plugins]]
  package = "@netlify/plugin-sitemap"

	[plugins.inputs]
	buildDir = "public"
	trailingSlash = true
	baseUrl = "https://bloodbee.space"
